namespace: architecture-suite-us-east1
replicaCount: 3
image:
  repository: ghcr.io/your-org/architecture-suite
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: architecture-suite.us-east1.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
env:
  REDIS_URL: redis://redis:6379/0
  DATABASE_URL: postgresql://user:password@postgres:5432/architecture_suite
  SECRET_KEY: "use-from-secret"
  ALGORITHM: HS256
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
