groups:
  - name: admin_service.rules
    rules:
      - alert: AdminServiceHighErrorRate
        expr: rate(http_requests_total{service="admin_service",status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate in admin_service
      - alert: AdminServiceHighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="admin_service"}[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency in admin_service
