apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: architecture-suite-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: architecture-suite-manager-binding
subjects:
  - kind: User
    name: manager@example.com # dynamically set from IdP
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: architecture-suite-manager
  apiGroup: rbac.authorization.k8s.io
