apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: architecture-suite
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: architecture-suite
  service:
    port: {{ .Values.service.port }}
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        threshold: 99
      - name: request-duration
        threshold: 0.2 # 200ms
