apiVersion: v1
kind: Pod
metadata:
  name: example-app
spec:
  containers:
    - name: app
      image: myapp:latest
      env:
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: password
