name: Deploy Architecture Suite

on:
  push:
    branches: [ main ]
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Deploy to Staging
        run: |
          helm upgrade --install architecture-suite ./services/architecture_suite/helm \
            --namespace architecture-suite --create-namespace \
            -f ./services/architecture_suite/.env.staging
  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Deploy to Production
        run: |
          helm upgrade --install architecture-suite ./services/architecture_suite/helm \
            --namespace architecture-suite --create-namespace \
            -f ./services/architecture_suite/.env.prod
  post-deploy-smoke:
    needs: [deploy-staging, deploy-production]
    runs-on: ubuntu-latest
    steps:
      - name: Health Check
        run: |
          curl --fail http://architecture-suite.local/health
      - name: CRUD Smoke Test
        run: |
          curl --fail -X POST http://architecture-suite.local/architecture-packages/
          curl --fail http://architecture-suite.local/architecture-packages/
      - name: Metrics Check
        run: |
          curl --fail http://architecture-suite.local/metrics
  rollback:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Helm Rollback
        run: |
          helm rollback architecture-suite || true
# Canary rollout is managed by Flagger/ArgoCD and can be adjusted in canary-rollout.yaml
