name: Python SDK CI
on:
  push:
    paths:
      - 'sdks/python/architecture_suite_sdk/**'
  pull_request:
    paths:
      - 'sdks/python/architecture_suite_sdk/**'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install SDK
        run: |
          cd sdks/python/architecture_suite_sdk
          pip install .
      - name: Run tests
        run: |
          cd sdks/python/architecture_suite_sdk
          pytest --maxfail=1 --disable-warnings -q
      - name: Build wheel
        run: |
          cd sdks/python/architecture_suite_sdk
          python setup.py bdist_wheel
